### PR TITLE
feat: cast params

### PR DESCRIPTION
**Pull request by wey-gu**
To cast param map from primitive to thrift bytes

## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### Issue(s) number: #273

### CODE REVIEW

**Comment by wey-gu** [comment]
- [ ] coverage
- [ ] example/docs

**Comment by BeautyyuYanli** [comment]
Some changes:
- method `BaseExecutor.execute_py_params` to use this feature
- not support list and dict yet

**Comment by BeautyyuYanli** [comment]
> But why not support List? That's actually my initial motivation of such change😋😂

The current usage for NList is wrong and I do not yet find the correct way to use NList

**Comment by wey-gu** [comment]
Aha, got it, :-p

Should be somewhere I made it wrong, but [this](https://github.com/vesoft-inc/nebula-python/issues/273) was verified working, I'll continue this part later when I have some time.

**Comment by BeautyyuYanli** [comment]
fixed NList

**Review by Nicole00 — APPROVED** [review]

**Pull request merged**
