### PR TITLE
feat: Add get_prop_names methods for scan results

### PR DESCRIPTION
**Pull request by haoxins**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

### CODE REVIEW

**Review by Nicole00 — DISMISSED** [review]
Great job! Thanks for your contribution.

**Comment by Nicole00** [comment]
Could you please check the ci for 3.12?

**Comment by wey-gu** [comment]
@haoxins could you please help run `pip-compile requirements/dev.in` to regenerate the dev.txt?

**Review by wey-gu — DISMISSED** [review]

**Comment by haoxins** [comment]
> @haoxins could you please help run `pip-compile requirements/dev.in` to regenerate the dev.txt?

@wey-gu done

**Comment by haoxins** [comment]
can we drop support for `<3.9`?

**Comment by wey-gu** [comment]
> can we drop support for `<3.9`?

I think it's fair(as of 2024 Jan) to drop py3.8.

cc @Nicole00 We need to add this to the release note, but it's to me reasonable for now to support py3.9+

**Review by wey-gu — APPROVED** [review]

**Review by wey-gu — APPROVED** [review]

**Pull request merged**
