### PR TITLE
fix session._connection none error

### LINKED ISSUE #249: connection is None in _remove_idle_unusable_session after session.close()
I have implement session pool feature to 2.6 refer to the session pool implementation in the master branch (#246), and i find the sessionpool may have the same issue.

after `session.release()`, `session.connection` is None, so `session._connection.close() ` will raise an error

https://github.com/vesoft-inc/nebula-python/blob/f028dfc68a01d6985c448cbb8c04e9c2b4b247f3/nebula3/gclient/net/SessionPool.py#L458-L461

https://github.com/vesoft-inc/nebula-python/blob/f028dfc68a01d6985c448cbb8c04e9c2b4b247f3/nebula3/gclient/net/Session.py#L228-L237

### PR DESCRIPTION
**Pull request by liuxiaocs7**
close #249

### CODE REVIEW

**Review by wey-gu — DISMISSED** [review]

**Comment by Aiee** [comment]
Hello @liuxiaocs7 

Thank you for bringing this to us.

When we release a session here we want to make sure two things: 1. the session is logged out 2. the connection is closed. The fix you proposed here didn't deal with the connection. You could just save the connection to a variable before releasing the session and close the connection later. Something like :

```
conn = session._connection
session.release()
conn.close()
```

**Comment by ELKTKJ** [comment]
> 



> Hello @liuxiaocs7
> 
> Thank you for bringing this to us.
> 
> When we release a session here we want to make sure two things: 1. the session is logged out 2. the connection is closed. The fix you proposed here didn't deal with the connection. You could just save the connection to a variable before releasing the session and close the connection later. Something like :
> 
> ```
> conn = session._connection
> session.release()
> conn.close()
> ```

Thanks for your kindly reply, got it, i'll fix

**Comment by liuxiaocs7** [comment]
> Hello @liuxiaocs7
> 
> Thank you for bringing this to us.
> 
> When we release a session here we want to make sure two things: 1. the session is logged out 2. the connection is closed. The fix you proposed here didn't deal with the connection. You could just save the connection to a variable before releasing the session and close the connection later. Something like :
> 
> ```
> conn = session._connection
> session.release()
> conn.close()
> ```

Thanks for your kindly reply, got it, i'll fix

**Review by wey-gu — APPROVED** [review]

**Review by Aiee — APPROVED** [review]
LGTM.

**Pull request merged**
