### PR TITLE
hotfix invoking the Node tags method

### PR DESCRIPTION
**Pull request by haoxins**
Sorry for introducing this in #302 

## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

### CODE REVIEW

**Comment by haoxins** [comment]
BTW, it seems that we don't use `@property` annotation in this package?
I prefer the way of using `@property`.

**Review by wey-gu — APPROVED** [review]
Thanks!
We may add test cases to cover it later :)

**Comment by wey-gu** [comment]
> BTW, it seems that we don't use `@property` annotation in this package?
> 
> I prefer the way of using `@property`.

Yes, this project was not initiated by pythonista, let's polish it together, feel free to drop PR on doing so!

**Comment by haoxins** [comment]
> > BTW, it seems that we don't use `@property` annotation in this package?
> > I prefer the way of using `@property`.
> 
> Yes, this project was not initiated by pythonista, let's polish it together, feel free to drop PR on doing so!

done

**Comment by wey-gu** [comment]
Sorry, after revisiting for a while, I think it's better not change .tags from a function into a `@property`.

- It's an API break change
- Relationship.edge_name and a bunch of other functions are in similar situations, we should either change or left unchanged to maintain consistency of the design

My suggestions would be:
- leave those getter functions function(without `@property`)
- optionally introduce _foo @property like Node._tags, Relationship._edge_name etc.
- Use `@property` for getters in next major version(that such break change is accepted) and to avoid breaking our user code.

What do you think @haoxins , please?

**Comment by haoxins** [comment]
> Sorry, after revisiting for a while, I think it's better not change .tags from a function into a `@property`.
> 
> * It's an API break change
> * Relationship.edge_name and a bunch of other functions are in similar situations, we should either change or left unchanged to maintain consistency of the design
> 
> My suggestions would be:
> 
> * leave those getter functions function(without `@property`)
> * optionally introduce _foo @Property like Node._tags, Relationship._edge_name etc.
> * Use `@property` for getters in next major version(that such break change is accepted) and to avoid breaking our user code.
> 
> What do you think @haoxins , please?

I had the same concerns before I pushed the commit.

I will just revert the commit for this PR

---

I want to do more naming changes in the future, will give a list in a Github issue.

**Comment by haoxins** [comment]
> Use @property for getters in next major version(that such break change is accepted) and to avoid breaking our user code.

> Yes, this project was not initiated by pythonista, let's polish it together, feel free to drop PR on doing so!

I think we can start a Github issue to track the changes that make this package more `Pythonic`.

**Comment by wey-gu** [comment]
> > Use @Property for getters in next major version(that such break change is accepted) and to avoid breaking our user code.
> 
> > Yes, this project was not initiated by pythonista, let's polish it together, feel free to drop PR on doing so!
> 
> I think we can start a Github issue to track the changes that make this package more `Pythonic`.

Yes, let's do it!!!

**Review by wey-gu — APPROVED** [review]

**Comment by wey-gu** [comment]
> > Sorry, after revisiting for a while, I think it's better not change .tags from a function into a `@property`.
> > 
> > * It's an API break change
> > * Relationship.edge_name and a bunch of other functions are in similar situations, we should either change or left unchanged to maintain consistency of the design
> > 
> > My suggestions would be:
> > 
> > * leave those getter functions function(without `@property`)
> > * optionally introduce _foo @Property like Node._tags, Relationship._edge_name etc.
> > * Use `@property` for getters in next major version(that such break change is accepted) and to avoid breaking our user code.
> > 
> > What do you think @haoxins , please?
> 
> I had the same concerns before I pushed the commit.
> 
> I will just revert the commit for this PR
> 
> I want to do more naming changes in the future, will give a list in a Github issue.

Please drop the main list issue as RFC ♥️.

**Comment by haoxins** [comment]
cc @Nicole00

**Comment by haoxins** [comment]
@Nicole00 take a look?

**Review by Nicole00 — APPROVED** [review]

**Pull request merged**
