### PR TITLE
feat: support publish docs to readthedocs

### PR DESCRIPTION
**Pull request by liuxiaocs7**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [X] enhancement

#### Issue(s) number: 

close: #289 

#### Description:

Hi, @wey-gu, plz help create project plug named `nebula-python` in readthedocs, and enable this option.

image

I have tested locally: 
- project: https://readthedocs.org/projects/liuxiaocs7-nebula-python/
- website: https://liuxiaocs7-nebula-python.readthedocs.io/en/latest/
- CI is triggered when docs is modified and the bot will add preview website in pr description.(According to https://github.com/readthedocs/actions/tree/v1/preview)

image

### CODE REVIEW

**Comment by wey-gu** [comment]
Amazing! Was about to be on a long flight, will apply for it ASAP when I am available!

**Comment by Nicole00** [comment]
can we just  expose the api in module nebula3.gclient?  the thrift api is useless for users.

**Comment by liuxiaocs7** [comment]
> can we just expose the api in module nebula3.gclient? the thrift api is useless for users.

Exclude some dirs by `EXCLUDE_PATTERNs`: https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html

**Review by Nicole00 — APPROVED** [review]
LGTM, great job!

**Pull request merged**
