### PR TITLE
Replace the protocol with header protocol

### PR DESCRIPTION
**Pull request by Aiee**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### Issue(s) number: 
Address https://github.com/vesoft-inc/nebula/issues/5191

#### Description:
Replace the protocol with header protocol

## Special notes for your reviewer, ex. impact of this fix, design document, etc:

> using compact protocol still cause nebula3.Exception.IOErrorException: Header transport frame was too large
`protocol = TCompactProtocol.TCompactProtocol(transport)`

### CODE REVIEW

**Comment by wey-gu** [comment]
is this related to https://github.com/vesoft-inc/nebula/issues/5190 or other issues actually?

**Comment by Aiee** [comment]
> is this related to [vesoft-inc/nebula#5190](https://github.com/vesoft-inc/nebula/issues/5190) or other issues actually?

My bad, I've updated the issue link https://github.com/vesoft-inc/nebula/issues/5191

**Comment by wey-gu** [comment]
> > is this related to [vesoft-inc/nebula#5190](https://github.com/vesoft-inc/nebula/issues/5190) or other issues actually?
> 
> My bad, I've updated the issue link [vesoft-inc/nebula#5191](https://github.com/vesoft-inc/nebula/issues/5191)

Thanks! So with header protocol, the client will not hang but exit in such huge-sized frame cases, right?

**Comment by Aiee** [comment]
> > > is this related to [vesoft-inc/nebula#5190](https://github.com/vesoft-inc/nebula/issues/5190) or other issues actually?
> > 
> > 
> > My bad, I've updated the issue link [vesoft-inc/nebula#5191](https://github.com/vesoft-inc/nebula/issues/5191)
> 
> Thanks! So with header protocol, the client will not hang but exit in such huge-sized frame cases, right?

Correct, an exception indicating the frame size is too large will be thrown.

**Comment by Nicole00** [comment]
storage client also needs consideration.

**Comment by Shylock-Hg** [comment]
https://github.com/vesoft-inc/nebula-cpp/blob/ee8d36add01c5e900d813fa9ab107ae114441cc4/src/client/Connection.cpp#L118
cpp client already use `THeaderProtocol`

**Review by wey-gu — APPROVED** [review]

**Pull request merged**
